/**
 * Security headers applied to every response. Consumed by:
 * - `src/middleware.ts` for on-demand (server-rendered) responses on every target;
 * - `integrations/security-headers.ts`, which writes them into the Vercel Build Output
 *   config for prerendered pages;
 * - `public/_headers` (Netlify and Cloudflare static assets), which mirrors this map and
 *   is kept in sync by a unit test.
 *
 * The Content-Security-Policy itself is generated by Astro (`security.csp` in
 * `astro.config.ts`) because it contains per-page hashes.
 */
export const securityHeaders: Readonly<Record<string, string>> = {
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), browsing-topics=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};
