/**
 * Security headers applied to every response.
 *
 * Single source of truth, consumed by:
 * - `src/middleware.ts` for on-demand (server-rendered) responses on every target
 * - `integrations/security-headers.ts` which writes them into the Vercel Build
 *   Output config for prerendered pages
 * - `public/_headers` (Netlify + Cloudflare static assets) mirrors this map and a
 *   unit test keeps the two in sync.
 *
 * The Content-Security-Policy itself is generated by Astro (`security.csp` in
 * `astro.config.ts`) because it contains per-page hashes.
 */
export const securityHeaders: Readonly<Record<string, string>> = {
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), browsing-topics=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};

/** Renders the map in Netlify/Cloudflare `_headers` file syntax. */
export function toHeadersFile(headers: Readonly<Record<string, string>> = securityHeaders): string {
  const lines = Object.entries(headers).map(([name, value]) => `  ${name}: ${value}`);
  return ['/*', ...lines].join('\n') + '\n';
}
